### PR TITLE
Task 1-ibrahim amr

### PR DESCRIPTION
**Pull request by IbrahimAmr-PR**

### CODE REVIEW

**Comment by ahmeddelattarr** [comment]
Nice commit msgs 👌🏻

**Comment by ahmeddelattarr** [comment]
But rename the file to be task1/your name

**Comment by Bassanthossamxx** [comment]
Great work , but add your name to the title of file name it : task1-yourname  inside folder of task 1

**Review by Bassanthossamxx — CHANGES_REQUESTED** [review]
add your mane to file name "Tak1-Yourname

**Review by Bassanthossamxx — COMMENTED** [review]
LGFM

**Review by Bassanthossamxx — APPROVED** [review]

**Pull request merged**
